---
development:
    dialect: postgres
    database: beds_development
    user: postgres
    password: postgres
    port: 5433
    host: localhost
    pool: 5
# test:
#   url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/beds_test?sslmode=disable"}}

production:
    dialect: postgres
    database: beds_prod
    user: postgres
    password: postgres
    port: 5433
    host: localhost
    pool: 5
